-- require "user.impatient"
require "user.options"
require "user.keymaps"
require "user.lazy"
require "user.autocommands"
require "user.colorscheme"
require "user.cmp"
require "user.telescope"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.gitsigns"
require "user.nvim-tree"
require "user.lualine"
-- require "user.illuminate"
require "user.toggleterm"
require "user.project"
require "user.indentline"
require "user.alpha"
require "user.lsp"
-- require "user.dap"
require "user.noice"
require "user.notify"
require "user.undo"
